/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import entities.Cours;
import service.CoursService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author pc
 */
public class CoursForm extends javax.swing.JInternalFrame {

    private CoursService cs = null;
    private DefaultTableModel model = null;
    private static int id = 0;
    public CoursForm() {
        initComponents();
         cs = new CoursService();
    this.setTitle("Gestion des cours");
    model = (DefaultTableModel) listeCours.getModel();
    loadCategoriesFromDatabase();
    load();
    }
    
    
    void load() {
    model.setRowCount(0); // Clear table
    for (Cours c : cs.findAll()) {
        model.addRow(new Object[]{
            c.getId(),
            c.getTitre(),
            c.getCategorie(),
            c.getDureeHeures()
        });
    }
   }
   void loadCategoriesFromDatabase() {
    comboCategorie.removeAllItems(); // Clear combo box
    comboCategorie.addItem(""); // Add empty first item
    
    // Use HashSet to avoid duplicates
    java.util.HashSet<String> uniqueCategories = new java.util.HashSet<>();
    
    // Get all courses
    List<Cours> coursList = cs.findAll();
    
    // Collect unique categories
    for (Cours cours : coursList) {
        String categorie = cours.getCategorie();
        if (categorie != null && !categorie.trim().isEmpty()) {
            uniqueCategories.add(categorie);
        }
    }
    
    // Add unique categories to combo box
    for (String categorie : uniqueCategories) {
        comboCategorie.addItem(categorie);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitre = new javax.swing.JTextField();
        comboCategorie = new javax.swing.JComboBox();
        txtDureeHeures = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeCours = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des cours");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("information cours"));

        jLabel1.setText("Titre :");

        jLabel2.setText("categorie : ");

        jLabel3.setText("dureeHeures : ");

        txtTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCategorie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDureeHeures))))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDureeHeures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        btnAjouter.setText("ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAjouter)
                .addGap(36, 36, 36)
                .addComponent(btnModifier)
                .addGap(45, 45, 45)
                .addComponent(btnSupprimer)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("liste des coures"));

        listeCours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titre", "categorie", "duree (heur)"
            }
        ));
        listeCours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeCoursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeCours);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitreActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
     String titre = txtTitre.getText();
    String categorie = comboCategorie.getSelectedItem().toString();
    String dureeText = txtDureeHeures.getText();
    
    if (titre.isEmpty() || categorie.isEmpty() || dureeText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!");
        return;
    }
    
    try {
        double duree = Double.parseDouble(dureeText);
        if (cs.create(new Cours(titre, categorie, duree))) {
            load();
            JOptionPane.showMessageDialog(this, "Cours ajouté avec succès!");
            // Clear fields
            txtTitre.setText("");
            comboCategorie.setSelectedIndex(0);
            txtDureeHeures.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout!");
        }
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Durée doit être un nombre!");
      }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        if (id == 0) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un cours à modifier!");
        return;
    }
    
    String titre = txtTitre.getText();
    String categorie = comboCategorie.getSelectedItem().toString();
    String dureeText = txtDureeHeures.getText();
    
    if (titre.isEmpty() || categorie.isEmpty() || dureeText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs!");
        return;
    }
    
    try {
        double duree = Double.parseDouble(dureeText);
        Cours cours = cs.findById(id);
        if (cours != null) {
            cours.setTitre(titre);
            cours.setCategorie(categorie);
            cours.setDureeHeures(duree);
            
            int reponse = JOptionPane.showConfirmDialog(this, 
                "Voulez-vous vraiment modifier ce cours?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION);
            
            if (reponse == JOptionPane.YES_OPTION) {
                if (cs.update(cours)) {
                    load();
                    JOptionPane.showMessageDialog(this, "Cours modifié avec succès!");
                    // Clear fields
                    txtTitre.setText("");
                    comboCategorie.setSelectedIndex(0);
                    txtDureeHeures.setText("");
                    id = 0;
                } else {
                    JOptionPane.showMessageDialog(this, "Erreur lors de la modification!");
                }
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Durée doit être un nombre!");
    }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
         if (id == 0) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un cours à supprimer!");
        return;
    }
    
    int reponse = JOptionPane.showConfirmDialog(this, 
        "Voulez-vous vraiment supprimer ce cours?",
        "Confirmation",
        JOptionPane.YES_NO_OPTION);
    
    if (reponse == JOptionPane.YES_OPTION) {
        Cours cours = cs.findById(id);
        if (cours != null) {
            if (cs.delete(cours)) {
                load();
                JOptionPane.showMessageDialog(this, "Cours supprimé avec succès!");
                // Clear fields
                txtTitre.setText("");
                comboCategorie.setSelectedIndex(0);
                txtDureeHeures.setText("");
                id = 0;
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression!");
            }
        }
    }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void listeCoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeCoursMouseClicked
        int selectedRow = listeCours.getSelectedRow();
        if (selectedRow >= 0) {
            id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
            txtTitre.setText(model.getValueAt(selectedRow, 1).toString());
            comboCategorie.setSelectedItem(model.getValueAt(selectedRow, 2).toString());
            txtDureeHeures.setText(model.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_listeCoursMouseClicked
          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox comboCategorie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeCours;
    private javax.swing.JTextField txtDureeHeures;
    private javax.swing.JTextField txtTitre;
    // End of variables declaration//GEN-END:variables
}
